### ISSUE TITLE
ReST Devs Team Project Repo, Problem Statement & Project Plan are Ready for Review

### ISSUE THREAD

**Issue by spartan7777** [spartan7777/ReST-Devs#1]
ReST Devs Team Project Repo, Problem Statement & Project Plan are Ready for Review

@pawaitemadisoncollege 

Some of the milestones for the ReSt Devs team have been completed.  
The team consists of Rob Adams, Sydney St. Clair, & Tosan Ogedengbe

Our repository is ready and there is a folder in there called Project Plan, that contains a project plan text file. The problem statement is laid out in the plan. Some of the items have already been checked off, and we are ready for critique and possible approval of the plan. 

On a side note - I created the repository following the steps from the Week 2 exercise. When I created this repo I noticed that I did not get a .idea folder or a .iml file created in Git even those these files were created locally by IntelliJ. I am not sure if this will cause issues down the line, but I wanted to point it out in case I caused this somehow and can correct it.

**Comment by pawaitemadisoncollege** [comment]
@spartan7777 @RobIsInSchool (unable to tag Sydney - is she a collaborator on this?)

- [ ] Remember to add your repository link to the team project list in the student repo: TeamProjects.md
- [ ] Consider your project readme.md as the homepage for your project. That is where you should include your problem statement, solution, scope.
- [ ] For approval for the scope of this project, I want to understand what resource/s your RESTful web service will provide and what operations will be available on those resources. For example, if I had a service that dealt with providing vehicle data. My resource might be Vehicles, with fields such as vin, make, model, safety features, vehicle history, etc.  My operations might be PUT, POST, GET (all, by vin, by make, by model, by some safety feature, etc.), DELETE (by id). I posted an larger example of this kind of documentation in the team project slack channel.
- [ ] I see a lot of reference to MVC in the project plan. Remember that the goal is to create a restful web service. If you have a web application that is your user guide and to demonstrate consuming the api, that's great! The project plan just seems very focused on a web application rather than the service.

**Comment by RobIsInSchool** [comment]
Hi @pawaitemadisoncollege , thanks so much for the feedback! We've made the following changes:

* Repo link has been added to Student repo
* Readme has been updated with problem statement, solution, and scope
* We will have two resources: industries and places. Industries will contain two fields: Name and Id. The data will come back as JSON with the industries sorted alphabetically. Places will contain 3 fields: Name, State, and Population. We will provide this as JSON as well. Users will have the option of parameterizing their queries (all of which will be GETs, to address that point) so that they can filter/sort by state and/or population. I hope that is sufficient!
* Now that we have a much clearer idea of what we're doing and how long we have to do it, our project plan has been updated accordingly.

**Comment by pawaitemadisoncollege** [comment]
Thanks for clarifying the resources and types. This detail should be provided in the readme as well! No need to respond here if the following are answered in the readme.md update:

1. If Places have Name, State, Population, how is it tied to industry? Should  there be an industry id on places? 
2. Industry GET - is this always a get all, or would it be possible to get by id? 
3. Consider adding more response types to increase your service complexity score (refer to rubric).
